# Generated by Django 5.2.7 on 2026-06-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_schedule_alter_appointment_unique_together_and_more'),
        ('payments', '0003_alter_order_status_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='appointments.appointment', verbose_name='الموعد'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='appointments.appointment', verbose_name='الموعد'),
        ),
    ]
